
logging:
  level:
    root: info
    com.springbootbasepackage.controller: debug


server:
  port: 8100
  compression:
    enabled: true
    mime-types:
      - application-json
      - application/xml
      - application/javascript
      - text/html
      - text/xml
      - text/plain
      - text/css
    min-response-size: 2048

xxl:
  job:
    admin:
      # XXL-Job 后台地址（你自己的）
      addresses: http://127.0.0.1:8101/xxl-job-admin
    executor:
      # 随便起，唯一就行
      appname: ${spring.application.name}
      # 本地日志路径
      logpath: ./logs/xxl-job
    # 执行器通讯令牌（默认就是这个，不用改）
    accessToken: default_token




spring:
  application:
    # 1. 必须配置服务名！控制台左侧会显示这个名字
    name: springboot-base
  cloud:
    sentinel:
      transport:
        # 2. 指向你的 Sentinel 控制台地址（本机就是 127.0.0.1:8080）
        dashboard: 127.0.0.1:8080
        # 3. 客户端通信端口（默认 8719，不冲突就不用改）
        port: 8719
      # 4. 开启 Web 适配，让 HTTP 请求被 Sentinel 拦截
      filter:
        enabled: true
        url-pattern: /*
      # 可选：启动时就连接控制台，避免延迟
      eager: true
  datasource:
    ufc:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dj_second_phase?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: 123456
    filters:
      stat,wall
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-wait: 10
        min-idle: 0
    timeout: 1000






